$ErrorActionPreference = "Stop"

$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path

$PT = "PT-0005"
$Title = "Foundation Completeness Theorem"
$Slug = "Foundation-Completeness-Theorem"

$Directory = Join-Path $RepositoryRoot "docs\canon\proofs\theorems"
$Path = Join-Path $Directory "$PT-$Slug.md"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " PT-0005 DOCUMENT CREATION" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Repository : $RepositoryRoot"
Write-Host "Target     : $Path"
Write-Host ""

if (Test-Path -LiteralPath $Path -PathType Leaf) {
    Write-Host "[INFO] PT-0005 already exists. No overwrite performed." -ForegroundColor Yellow
    Get-Item -LiteralPath $Path |
        Select-Object FullName, Length, LastWriteTime
    exit 0
}

New-Item -ItemType Directory -Path $Directory -Force |
    Out-Null

$Lines = @(
    "# PT-0005 - Foundation Completeness Theorem"
    ""
    "**Document Identifier:** PT-0005"
    ""
    "**Title:** Foundation Completeness Theorem"
    ""
    "**Classification:** Foundational Theorem"
    ""
    "**Programme:** Mathematical Proof Programme (MPP)"
    ""
    "**Layer:** Certified Mathematical Foundation (CMF)"
    ""
    "**Status:** Draft"
    ""
    "**Version:** 1.0"
    ""
    "**Authority:** SMOF Constitution"
    ""
    "**Governing Standard:** SCS-0001 Foundation Audit Framework"
    ""
    "---"
    ""
    "# 1. Purpose"
    ""
    "This theorem establishes Foundation Completeness relative to the Certified Mathematical Foundation defined by PA-0001 and the constitutionally certified composition rules of SMOF."
    ""
    "# 2. Scope"
    ""
    "This theorem applies to formally admitted constructs within the Certified Mathematical Foundation. It does not assert completeness with respect to all mathematics or any external foundational system."
    ""
    "# 3. Normative References"
    ""
    "- SMOF Constitution"
    "- SMOF Canon"
    "- PA-0001 - Primitive Sufficiency Axiom"
    "- PL-0001 - Operator Closure Lemma"
    "- PT-0001 - Primitive Sufficiency Theorem"
    "- PT-0002 - Operator Composition Theorem"
    "- PT-0003 - Runtime Correctness Theorem"
    "- PT-0004 - Execution Graph Correctness Theorem"
    "- SCS-0001 Foundation Audit Framework"
    ""
    "# 4. Primitive Foundation"
    ""
    "The Certified Mathematical Foundation is generated from the primitive set"
    ""
    "P = {E, O, P, R}"
    ""
    "where E denotes MathematicalEntity, O denotes MathematicalObject, P denotes MathematicalOperator, and R denotes MathematicalRuntime."
    ""
    "# 5. Certified Composition"
    ""
    "Let C denote the collection of constitutionally certified finite composition rules permitted within SMOF."
    ""
    "Let Gen(P,C) denote the smallest class containing the primitive set and closed under every certified composition rule in C."
    ""
    "# 6. Formal Statement"
    ""
    "Let F_SMOF denote the class of mathematical constructs formally admitted by the Certified Mathematical Foundation."
    ""
    "Then"
    ""
    "F_SMOF is a subset of Gen(P,C)."
    ""
    "Every formally admitted SMOF construct is obtainable through finite certified composition of the primitive set under the certified composition rules."
    ""
    "# 7. Proof"
    ""
    "The proof proceeds by structural induction on finite construction depth."
    ""
    "## 7.1 Base Case"
    ""
    "For construction depth zero, the construct is one of the primitive constructs E, O, P, or R. Therefore it belongs to P and hence to Gen(P,C)."
    ""
    "## 7.2 Inductive Hypothesis"
    ""
    "Assume every certified construct of construction depth at most n belongs to Gen(P,C)."
    ""
    "## 7.3 Inductive Step"
    ""
    "Let C have construction depth n+1. By the definition of finite certified construction, C is obtained by applying a certified composition rule to constructs of depth at most n."
    ""
    "By the inductive hypothesis, each constituent construct belongs to Gen(P,C)."
    ""
    "PL-0001 establishes operator closure, while PT-0002 establishes correctness of finite certified operator composition. Therefore the resulting construct also belongs to Gen(P,C)."
    ""
    "Hence the proposition holds for n+1."
    ""
    "# 8. Runtime and Execution Preservation"
    ""
    "PT-0003 establishes runtime correctness for certified constructs, while PT-0004 establishes correctness of their execution graphs. Therefore runtime execution and graph representation preserve the certified mathematical construction."
    ""
    "# 9. Main Result"
    ""
    "By structural induction,"
    ""
    "F_SMOF is a subset of Gen(P,C)."
    ""
    "Therefore every formally admitted SMOF construct is derivable from the primitive vocabulary under constitutionally certified finite composition."
    ""
    "**QED.**"
    ""
    "# 10. Limitations"
    ""
    "This theorem establishes completeness only relative to the Certified Mathematical Foundation and its certified composition rules."
    ""
    "It does not claim that all mathematical objects are representable by SMOF, nor that SMOF is equivalent to ZFC, type theory, or another external foundational system."
    ""
    "# 11. Consequences"
    ""
    "Acceptance of PT-0005 establishes that higher-order SMOF constructs may be derived through certified composition rather than requiring uncontrolled expansion of the primitive vocabulary."
    ""
    "The theorem therefore supports the constitutional principle that composition is preferred over primitive expansion."
    ""
    "# 12. Dependency Chain"
    ""
    "```text"
    "PA-0001"
    "   |"
    "   v"
    "PL-0001"
    "   |"
    "   v"
    "PT-0001"
    "   |"
    "   v"
    "PT-0002"
    "   |"
    "   v"
    "PT-0003"
    "   |"
    "   v"
    "PT-0004"
    "   |"
    "   v"
    "PT-0005"
    "```"
    ""
    "# 13. Constitutional Alignment"
    ""
    "This theorem implements the constitutional principles that mathematics precedes implementation, foundational concepts remain minimal, composition is preferred over primitive expansion, and certified semantics govern execution."
    ""
    "# 14. Governance"
    ""
    "Any proposal affecting the primitive basis, composition rules, assumptions, or conclusions of PT-0005 shall require mathematical justification, dependency analysis, impact analysis, review of affected Foundation Contracts, Foundation Audit, certification, and publication within the SMOF Canon."
    ""
    "# 15. Theorem Status"
    ""
    "**Identifier:** PT-0005"
    ""
    "**Classification:** Foundational Theorem"
    ""
    "**Programme:** Mathematical Proof Programme"
    ""
    "**Layer:** Certified Mathematical Foundation"
    ""
    "**Status:** Draft"
    ""
    "**Version:** 1.0"
    ""
    "**Authority:** SMOF Constitution"
    ""
    "**Canonical Location:**"
    ""
    "`docs/canon/proofs/theorems/PT-0005-Foundation-Completeness-Theorem.md`"
    ""
    "# 16. Certification Note"
    ""
    "PT-0005 establishes Foundation Completeness relative to the Certified Mathematical Foundation. It is subject to Foundation Audit and certification before becoming a normative component of the SMOF Canon."
)

$Content = [String]::Join([Environment]::NewLine, $Lines)

[System.IO.File]::WriteAllText(
    $Path,
    $Content,
    [System.Text.UTF8Encoding]::new($false)
)

if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
    throw "PT-0005 creation failed."
}

Write-Host ""
Write-Host "[PASS] PT-0005 created using UTF-8 without BOM." -ForegroundColor Green

Get-Item -LiteralPath $Path |
    Select-Object FullName, Length, LastWriteTime